### ISSUE TITLE
Introduction of `--prefix` argument fails in supermeans.py.

### ISSUE THREAD

**Issue by VidyaVR** [jonnyhtw/scripts#1]
Introduction of `--prefix` argument fails in supermeans.py.

**Comment by jonnyhtw** [comment]
Thanks for that, will investigate...

**Comment by jonnyhtw** [comment]
I see you've already fixed this for me, thanks! I'll close this issue now.

**Comment by jonnyhtw** [comment]
fixed by #2 , thanks @vv1610 🎉
